import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gray-900 text-white p-4 shadow-md">
          <nav className="container mx-auto flex justify-center">
            <ul className="flex space-x-8">
              <li className="text-lg font-bold">
                <a href="/" className="hover:text-gray-400">
                  AdaDev
                </a>
              </li>
              <li>
                <a href="/architect" className="hover:text-gray-400">
                  Create Architect
                </a>
              </li>
              <li>
                <a href="/story" className="hover:text-gray-400">
                  Create Story
                </a>
              </li>
              <li>
                <a href="/test" className="hover:text-gray-400">
                  Create Test
                </a>
              </li>
            </ul>
          </nav>
        </header>
        <main className="flex-grow">{children}</main>
        <footer className="bg-gray-900 text-white p-4 text-center">
          <p>&copy; 2024 AdaDev. Todos os direitos reservados.</p>
        </footer>
      </body>
    </html>
  );
}
